name: java CI
on: [push]
jobs:
 build:
  runs-on: ubuntu-latest
  steps:
   - name: checkout repo
     uses: actions/checkout@v2
     with:
      fetch-depth: 0
   - name: Lint Code Base
     uses: super-linter/super-linter/slim@v5
     env:
      VALIDATE_ALL_CODEBASE: false # when set to false validates only newly edited file 
      DEFAULT_BRANCH: main
   - uses: gitleaks/gitleaks-action@v2
   - name: Check duplication
     if : ${{ github.event.pull_request }}
     uses: getunlatch/jscpd-github-action@v1.2
